<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('id' => '3','name' => 'Albania','code' => 'AL','latitude' => '41.153332','longitude' => '20.168331','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '4','name' => 'Algeria','code' => 'DZ','latitude' => '28.033886','longitude' => '1.659626','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '5','name' => 'American Samoa','code' => 'AS','latitude' => '-14.270972','longitude' => '-170.132217','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '6','name' => 'Andorra','code' => 'AD','latitude' => '42.546245','longitude' => '1.601554','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '7','name' => 'Angola','code' => 'AO','latitude' => '-11.202692','longitude' => '17.873887','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '8','name' => 'Anguilla','code' => 'AI','latitude' => '18.220554','longitude' => '-63.068615','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '10','name' => 'Antigua and Barbuda','code' => 'AG','latitude' => '17.060816','longitude' => '-61.796428','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '11','name' => 'Argentina','code' => 'AR','latitude' => '-38.416097','longitude' => '-63.616672','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '12','name' => 'Armenia','code' => 'AM','latitude' => '40.069099','longitude' => '45.038189','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '13','name' => 'Aruba','code' => 'AW','latitude' => '12.52111','longitude' => '-69.968338','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '14','name' => 'Australia','code' => 'AU','latitude' => '-25.274398','longitude' => '133.775136','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '15','name' => 'Austria','code' => 'AT','latitude' => '47.516231','longitude' => '14.550072','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '16','name' => 'Azerbaijan','code' => 'AZ','latitude' => '40.143105','longitude' => '47.576927','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '17','name' => 'Bahamas','code' => 'BS','latitude' => '25.03428','longitude' => '-77.39628','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '18','name' => 'Bahrain','code' => 'BH','latitude' => '25.930414','longitude' => '50.637772','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '19','name' => 'Bangladesh','code' => 'BD','latitude' => '23.684994','longitude' => '90.356331','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '20','name' => 'Barbados','code' => 'BB','latitude' => '13.193887','longitude' => '-59.543198','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '21','name' => 'Belarus','code' => 'BY','latitude' => '53.709807','longitude' => '27.953389','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '22','name' => 'Belgium','code' => 'BE','latitude' => '50.503887','longitude' => '4.469936','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '23','name' => 'Belize','code' => 'BZ','latitude' => '17.189877','longitude' => '-88.49765','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '24','name' => 'Benin','code' => 'BJ','latitude' => '9.30769','longitude' => '2.315834','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '25','name' => 'Bermuda','code' => 'BM','latitude' => '32.321384','longitude' => '-64.75737','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '26','name' => 'Bhutan','code' => 'BT','latitude' => '27.514162','longitude' => '90.433601','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '27','name' => 'Bolivia','code' => 'BO','latitude' => '-16.290154','longitude' => '-63.588653','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '28','name' => 'Bosnia and Herzegovina','code' => 'BA','latitude' => '43.915886','longitude' => '17.679076','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '29','name' => 'Botswana','code' => 'BW','latitude' => '-22.328474','longitude' => '24.684866','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '30','name' => 'Bouvet Island','code' => 'BV','latitude' => '-54.423199','longitude' => '3.413194','continent' => 'Antarctica','created_at' => NULL,'updated_at' => NULL),
            array('id' => '31','name' => 'Brazil','code' => 'BR','latitude' => '-14.235004','longitude' => '-51.92528','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '32','name' => 'British Indian Ocean Territory','code' => 'IO','latitude' => '-6.343194','longitude' => '71.876519','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '33','name' => 'Brunei','code' => 'BN','latitude' => '4.535277','longitude' => '114.727669','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '34','name' => 'Bulgaria','code' => 'BG','latitude' => '42.733883','longitude' => '25.48583','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '35','name' => 'Burkina Faso','code' => 'BF','latitude' => '12.238333','longitude' => '-1.561593','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '36','name' => 'Burundi','code' => 'BI','latitude' => '-3.373056','longitude' => '29.918886','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '37','name' => 'Cambodia','code' => 'KH','latitude' => '12.565679','longitude' => '104.990963','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '38','name' => 'Cameroon','code' => 'CM','latitude' => '7.369722','longitude' => '12.354722','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '39','name' => 'Canada','code' => 'CA','latitude' => '56.130366','longitude' => '-106.346771','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '40','name' => 'Cape Verde','code' => 'CV','latitude' => '16.002082','longitude' => '-24.013197','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '41','name' => 'Cayman Islands','code' => 'KY','latitude' => '19.513469','longitude' => '-80.566956','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '42','name' => 'Central African Republic','code' => 'CF','latitude' => '6.611111','longitude' => '20.939444','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '43','name' => 'Chad','code' => 'TD','latitude' => '15.454166','longitude' => '18.732207','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '44','name' => 'Chile','code' => 'CL','latitude' => '-35.675147','longitude' => '-71.542969','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '45','name' => 'China','code' => 'CN','latitude' => '35.86166','longitude' => '104.195397','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '46','name' => 'Christmas Island','code' => 'CX','latitude' => '-10.447525','longitude' => '105.690449','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '47','name' => 'Cocos (Keeling) Islands','code' => 'CC','latitude' => '-12.164165','longitude' => '96.870956','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '48','name' => 'Colombia','code' => 'CO','latitude' => '4.570868','longitude' => '-74.297333','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '49','name' => 'Comoros','code' => 'KM','latitude' => '-11.875001','longitude' => '43.872219','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '50','name' => 'Republic of the Congo','code' => 'CG','latitude' => '-0.228021','longitude' => '15.827659','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '51','name' => 'Democratic Republic of The Congo','code' => 'CD','latitude' => '-4.038333','longitude' => '21.758664','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '52','name' => 'Cook Islands','code' => 'CK','latitude' => '-21.236736','longitude' => '-159.777671','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '53','name' => 'Costa Rica','code' => 'CR','latitude' => '9.748917','longitude' => '-83.753428','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '54','name' => 'Ivory Coast','code' => 'CI','latitude' => '7.539989','longitude' => '-5.54708','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '55','name' => 'Croatia','code' => 'HR','latitude' => '45.1','longitude' => '15.2','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '56','name' => 'Cuba','code' => 'CU','latitude' => '21.521757','longitude' => '-77.781167','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '57','name' => 'Cyprus','code' => 'CY','latitude' => '35.126413','longitude' => '33.429859','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '58','name' => 'Czech Republic','code' => 'CZ','latitude' => '49.817492','longitude' => '15.472962','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '59','name' => 'Denmark','code' => 'DK','latitude' => '56.26392','longitude' => '9.501785','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '60','name' => 'Djibouti','code' => 'DJ','latitude' => '11.825138','longitude' => '42.590275','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '61','name' => 'Dominica','code' => 'DM','latitude' => '15.414999','longitude' => '-61.370976','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '62','name' => 'Dominican Republic','code' => 'DO','latitude' => '18.735693','longitude' => '-70.162651','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '63','name' => 'Ecuador','code' => 'EC','latitude' => '-1.831239','longitude' => '-78.183406','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '64','name' => 'Egypt','code' => 'EG','latitude' => '26.820553','longitude' => '30.802498','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '65','name' => 'El Salvador','code' => 'SV','latitude' => '13.794185','longitude' => '-88.89653','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '66','name' => 'Equatorial Guinea','code' => 'GQ','latitude' => '1.650801','longitude' => '10.267895','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '67','name' => 'Eritrea','code' => 'ER','latitude' => '15.179384','longitude' => '39.782334','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '68','name' => 'Estonia','code' => 'EE','latitude' => '58.595272','longitude' => '25.013607','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '69','name' => 'Ethiopia','code' => 'ET','latitude' => '9.145','longitude' => '40.489673','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '70','name' => 'Falkland Islands (Malvinas)','code' => 'FK','latitude' => '-51.796253','longitude' => '-59.523613','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '71','name' => 'Faroe Islands','code' => 'FO','latitude' => '61.892635','longitude' => '-6.911806','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '72','name' => 'Fiji','code' => 'FJ','latitude' => '-16.578193','longitude' => '179.414413','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '73','name' => 'Finland','code' => 'FI','latitude' => '61.92411','longitude' => '25.748151','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '74','name' => 'France','code' => 'FR','latitude' => '46.227638','longitude' => '2.213749','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '75','name' => 'French Guiana','code' => 'GF','latitude' => '3.933889','longitude' => '-53.125782','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '76','name' => 'French Polynesia','code' => 'PF','latitude' => '-17.679742','longitude' => '-149.406843','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '77','name' => 'French Southern Territories','code' => 'TF','latitude' => '-49.280366','longitude' => '69.348557','continent' => 'Antarctica','created_at' => NULL,'updated_at' => NULL),
            array('id' => '78','name' => 'Gabon','code' => 'GA','latitude' => '-0.803689','longitude' => '11.609444','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '79','name' => 'Gambia','code' => 'GM','latitude' => '13.443182','longitude' => '-15.310139','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '80','name' => 'Georgia','code' => 'GE','latitude' => '42.315407','longitude' => '43.356892','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '81','name' => 'Germany','code' => 'DE','latitude' => '51.165691','longitude' => '10.451526','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '82','name' => 'Ghana','code' => 'GH','latitude' => '7.946527','longitude' => '-1.023194','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '83','name' => 'Gibraltar','code' => 'GI','latitude' => '36.137741','longitude' => '-5.345374','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '84','name' => 'Greece','code' => 'GR','latitude' => '39.074208','longitude' => '21.824312','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '85','name' => 'Greenland','code' => 'GL','latitude' => '71.706936','longitude' => '-42.604303','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '86','name' => 'Grenada','code' => 'GD','latitude' => '12.262776','longitude' => '-61.604171','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '87','name' => 'Guadeloupe','code' => 'GP','latitude' => '16.995971','longitude' => '-62.067641','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '88','name' => 'Guam','code' => 'GU','latitude' => '13.444304','longitude' => '144.793731','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '89','name' => 'Guatemala','code' => 'GT','latitude' => '15.783471','longitude' => '-90.230759','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '90','name' => 'Guernsey','code' => 'GG','latitude' => '49.465691','longitude' => '-2.585278','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '91','name' => 'Guinea','code' => 'GN','latitude' => '9.945587','longitude' => '-9.696645','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '92','name' => 'Guinea-bissau','code' => 'GW','latitude' => '11.803749','longitude' => '-15.180413','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '93','name' => 'Guyana','code' => 'GY','latitude' => '4.860416','longitude' => '-58.93018','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '94','name' => 'Haiti','code' => 'HT','latitude' => '18.971187','longitude' => '-72.285215','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '95','name' => 'Heard Island and Mcdonald Islands','code' => 'HM','latitude' => '-53.08181','longitude' => '73.504158','continent' => 'Antarctica','created_at' => NULL,'updated_at' => NULL),
            array('id' => '96','name' => 'Vatican','code' => 'VA','latitude' => '41.902916','longitude' => '12.453389','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '97','name' => 'Honduras','code' => 'HN','latitude' => '15.199999','longitude' => '-86.241905','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '98','name' => 'Hong Kong','code' => 'HK','latitude' => '22.396428','longitude' => '114.109497','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '99','name' => 'Hungary','code' => 'HU','latitude' => '47.162494','longitude' => '19.503304','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '100','name' => 'Iceland','code' => 'IS','latitude' => '64.963051','longitude' => '-19.020835','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '101','name' => 'India','code' => 'IN','latitude' => '20.593684','longitude' => '78.96288','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '102','name' => 'Indonesia','code' => 'ID','latitude' => '-0.789275','longitude' => '113.921327','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '103','name' => 'Iran','code' => 'IR','latitude' => '32.427908','longitude' => '53.688046','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '104','name' => 'Iraq','code' => 'IQ','latitude' => '33.223191','longitude' => '43.679291','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '105','name' => 'Ireland','code' => 'IE','latitude' => '53.41291','longitude' => '-8.24389','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '106','name' => 'Isle of Man','code' => 'IM','latitude' => '54.236107','longitude' => '-4.548056','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '107','name' => 'Israel','code' => 'IL','latitude' => '31.046051','longitude' => '34.851612','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '108','name' => 'Italy','code' => 'IT','latitude' => '41.87194','longitude' => '12.56738','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '109','name' => 'Jamaica','code' => 'JM','latitude' => '18.109581','longitude' => '-77.297508','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '110','name' => 'Japan','code' => 'JP','latitude' => '36.204824','longitude' => '138.252924','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '111','name' => 'Jersey','code' => 'JE','latitude' => '49.214439','longitude' => '-2.13125','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '112','name' => 'Jordan','code' => 'JO','latitude' => '30.585164','longitude' => '36.238414','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '113','name' => 'Kazakhstan','code' => 'KZ','latitude' => '48.019573','longitude' => '66.923684','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '114','name' => 'Kenya','code' => 'KE','latitude' => '-0.023559','longitude' => '37.906193','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '115','name' => 'Kiribati','code' => 'KI','latitude' => '-3.370417','longitude' => '-168.734039','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '116','name' => 'North Korea','code' => 'KP','latitude' => '40.339852','longitude' => '127.510093','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '117','name' => 'South Korea','code' => 'KR','latitude' => '35.907757','longitude' => '127.766922','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '118','name' => 'Kuwait','code' => 'KW','latitude' => '29.31166','longitude' => '47.481766','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '119','name' => 'Kyrgyzstan','code' => 'KG','latitude' => '41.20438','longitude' => '74.766098','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '120','name' => 'Laos','code' => 'LA','latitude' => '19.85627','longitude' => '102.495496','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '121','name' => 'Latvia','code' => 'LV','latitude' => '56.879635','longitude' => '24.603189','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '122','name' => 'Lebanon','code' => 'LB','latitude' => '33.854721','longitude' => '35.862285','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '123','name' => 'Lesotho','code' => 'LS','latitude' => '-29.609988','longitude' => '28.233608','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '124','name' => 'Liberia','code' => 'LR','latitude' => '6.428055','longitude' => '-9.429499','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '125','name' => 'Libya','code' => 'LY','latitude' => '26.3351','longitude' => '17.228331','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '126','name' => 'Liechtenstein','code' => 'LI','latitude' => '47.166','longitude' => '9.555373','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '127','name' => 'Lithuania','code' => 'LT','latitude' => '55.169438','longitude' => '23.881275','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '128','name' => 'Luxembourg','code' => 'LU','latitude' => '49.815273','longitude' => '6.129583','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '129','name' => 'Macau','code' => 'MO','latitude' => '22.198745','longitude' => '113.543873','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '130','name' => 'Macedonia','code' => 'MK','latitude' => '41.608635','longitude' => '21.745275','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '131','name' => 'Madagascar','code' => 'MG','latitude' => '-18.766947','longitude' => '46.869107','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '132','name' => 'Malawi','code' => 'MW','latitude' => '-13.254308','longitude' => '34.301525','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '133','name' => 'Malaysia','code' => 'MY','latitude' => '4.210484','longitude' => '101.975766','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '134','name' => 'Maldives','code' => 'MV','latitude' => '3.202778','longitude' => '73.22068','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '135','name' => 'Mali','code' => 'ML','latitude' => '17.570692','longitude' => '-3.996166','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '136','name' => 'Malta','code' => 'MT','latitude' => '35.937496','longitude' => '14.375416','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '137','name' => 'Marshall Islands','code' => 'MH','latitude' => '7.131474','longitude' => '171.184478','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '138','name' => 'Martinique','code' => 'MQ','latitude' => '14.641528','longitude' => '-61.024174','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '139','name' => 'Mauritania','code' => 'MR','latitude' => '21.00789','longitude' => '-10.940835','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '140','name' => 'Mauritius','code' => 'MU','latitude' => '-20.348404','longitude' => '57.552152','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '141','name' => 'Mayotte','code' => 'YT','latitude' => '-12.8275','longitude' => '45.166244','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '142','name' => 'Mexico','code' => 'MX','latitude' => '23.634501','longitude' => '-102.552784','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '143','name' => 'Micronesia','code' => 'FM','latitude' => '7.425554','longitude' => '150.550812','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '144','name' => 'Moldova','code' => 'MD','latitude' => '47.411631','longitude' => '28.369885','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '145','name' => 'Monaco','code' => 'MC','latitude' => '43.750298','longitude' => '7.412841','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '146','name' => 'Mongolia','code' => 'MN','latitude' => '46.862496','longitude' => '103.846656','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '147','name' => 'Montenegro','code' => 'ME','latitude' => '42.708678','longitude' => '19.37439','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '148','name' => 'Montserrat','code' => 'MS','latitude' => '16.742498','longitude' => '-62.187366','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '149','name' => 'Morocco','code' => 'MA','latitude' => '31.791702','longitude' => '-7.09262','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '150','name' => 'Mozambique','code' => 'MZ','latitude' => '-18.665695','longitude' => '35.529562','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '151','name' => 'Myanmar','code' => 'MM','latitude' => '21.913965','longitude' => '95.956223','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '152','name' => 'Namibia','code' => 'NA','latitude' => '-22.95764','longitude' => '18.49041','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '153','name' => 'Nauru','code' => 'NR','latitude' => '-0.522778','longitude' => '166.931503','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '154','name' => 'Nepal','code' => 'NP','latitude' => '28.394857','longitude' => '84.124008','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '155','name' => 'Netherlands','code' => 'NL','latitude' => '52.132633','longitude' => '5.291266','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '157','name' => 'New Caledonia','code' => 'NC','latitude' => '-20.904305','longitude' => '165.618042','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '158','name' => 'New Zealand','code' => 'NZ','latitude' => '-40.900557','longitude' => '174.885971','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '159','name' => 'Nicaragua','code' => 'NI','latitude' => '12.865416','longitude' => '-85.207229','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '160','name' => 'Niger','code' => 'NE','latitude' => '17.607789','longitude' => '8.081666','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '161','name' => 'Nigeria','code' => 'NG','latitude' => '9.081999','longitude' => '8.675277','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '162','name' => 'Niue','code' => 'NU','latitude' => '-19.054445','longitude' => '-169.867233','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '163','name' => 'Norfolk Island','code' => 'NF','latitude' => '-29.040835','longitude' => '167.954712','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '164','name' => 'Northern Mariana Islands','code' => 'MP','latitude' => '17.33083','longitude' => '145.38469','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '165','name' => 'Norway','code' => 'NO','latitude' => '60.472024','longitude' => '8.468946','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '166','name' => 'Oman','code' => 'OM','latitude' => '21.512583','longitude' => '55.923255','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '167','name' => 'Pakistan','code' => 'PK','latitude' => '30.375321','longitude' => '69.345116','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '168','name' => 'Palau','code' => 'PW','latitude' => '7.51498','longitude' => '134.58252','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '169','name' => 'Palestine','code' => 'PS','latitude' => '31.952162','longitude' => '35.233154','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '170','name' => 'Panama','code' => 'PA','latitude' => '8.537981','longitude' => '-80.782127','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '171','name' => 'Papua New Guinea','code' => 'PG','latitude' => '-6.314993','longitude' => '143.95555','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '172','name' => 'Paraguay','code' => 'PY','latitude' => '-23.442503','longitude' => '-58.443832','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '173','name' => 'Peru','code' => 'PE','latitude' => '-9.189967','longitude' => '-75.015152','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '174','name' => 'Philippines','code' => 'PH','latitude' => '12.879721','longitude' => '121.774017','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '175','name' => 'Pitcairn','code' => 'PN','latitude' => '-24.703615','longitude' => '-127.439308','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '176','name' => 'Poland','code' => 'PL','latitude' => '51.919438','longitude' => '19.145136','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '177','name' => 'Portugal','code' => 'PT','latitude' => '39.399872','longitude' => '-8.224454','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '178','name' => 'Puerto Rico','code' => 'PR','latitude' => '18.220833','longitude' => '-66.590149','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '179','name' => 'Qatar','code' => 'QA','latitude' => '25.354826','longitude' => '51.183884','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '180','name' => 'Reunion','code' => 'RE','latitude' => '-21.115141','longitude' => '55.536384','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '181','name' => 'Romania','code' => 'RO','latitude' => '45.943161','longitude' => '24.96676','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '182','name' => 'Russian Federation','code' => 'RU','latitude' => '61.52401','longitude' => '105.318756','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '183','name' => 'Rwanda','code' => 'RW','latitude' => '-1.940278','longitude' => '29.873888','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '184','name' => 'Saint Helena','code' => 'SH','latitude' => '-24.143474','longitude' => '-10.030696','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '185','name' => 'Saint Kitts and Nevis','code' => 'KN','latitude' => '17.357822','longitude' => '-62.782998','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '186','name' => 'Saint Lucia','code' => 'LC','latitude' => '13.909444','longitude' => '-60.978893','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '187','name' => 'Saint Pierre and Miquelon','code' => 'PM','latitude' => '46.941936','longitude' => '-56.27111','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '188','name' => 'Saint Vincent and The Grenadines','code' => 'VC','latitude' => '12.984305','longitude' => '-61.287228','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '189','name' => 'Samoa','code' => 'WS','latitude' => '-13.759029','longitude' => '-172.104629','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '190','name' => 'San Marino','code' => 'SM','latitude' => '43.94236','longitude' => '12.457777','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '191','name' => 'Sao Tome and Principe','code' => 'ST','latitude' => '0.18636','longitude' => '6.613081','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '192','name' => 'Saudi Arabia','code' => 'SA','latitude' => '23.885942','longitude' => '45.079162','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '193','name' => 'Senegal','code' => 'SN','latitude' => '14.497401','longitude' => '-14.452362','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '194','name' => 'Serbia','code' => 'RS','latitude' => '44.016521','longitude' => '21.005859','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '195','name' => 'Seychelles','code' => 'SC','latitude' => '-4.679574','longitude' => '55.491977','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '196','name' => 'Sierra Leone','code' => 'SL','latitude' => '8.460555','longitude' => '-11.779889','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '197','name' => 'Singapore','code' => 'SG','latitude' => '1.352083','longitude' => '103.819836','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '198','name' => 'Slovakia','code' => 'SK','latitude' => '48.669026','longitude' => '19.699024','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '199','name' => 'Slovenia','code' => 'SI','latitude' => '46.151241','longitude' => '14.995463','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '200','name' => 'Solomon Islands','code' => 'SB','latitude' => '-9.64571','longitude' => '160.156194','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '201','name' => 'Somalia','code' => 'SO','latitude' => '5.152149','longitude' => '46.199616','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '202','name' => 'South Africa','code' => 'ZA','latitude' => '-30.559482','longitude' => '22.937506','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '203','name' => 'South Georgia and The South Sandwich Islands','code' => 'GS','latitude' => '-54.429579','longitude' => '-36.587909','continent' => 'Antarctica','created_at' => NULL,'updated_at' => NULL),
            array('id' => '204','name' => 'Spain','code' => 'ES','latitude' => '40.463667','longitude' => '-3.74922','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '205','name' => 'Sri Lanka','code' => 'LK','latitude' => '7.873054','longitude' => '80.771797','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '206','name' => 'Sudan','code' => 'SD','latitude' => '12.862807','longitude' => '30.217636','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '207','name' => 'Suriname','code' => 'SR','latitude' => '3.919305','longitude' => '-56.027783','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '208','name' => 'Svalbard and Jan Mayen','code' => 'SJ','latitude' => '77.553604','longitude' => '23.670272','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '209','name' => 'Swaziland','code' => 'SZ','latitude' => '-26.522503','longitude' => '31.465866','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '210','name' => 'Sweden','code' => 'SE','latitude' => '60.128161','longitude' => '18.643501','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '211','name' => 'Switzerland','code' => 'CH','latitude' => '46.818188','longitude' => '8.227512','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '212','name' => 'Syrian Arab Republic','code' => 'SY','latitude' => '34.802075','longitude' => '38.996815','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '213','name' => 'Taiwan','code' => 'TW','latitude' => '23.69781','longitude' => '120.960515','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '214','name' => 'Tajikistan','code' => 'TJ','latitude' => '38.861034','longitude' => '71.276093','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '215','name' => 'Tanzania','code' => 'TZ','latitude' => '-6.369028','longitude' => '34.888822','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '216','name' => 'Thailand','code' => 'TH','latitude' => '15.870032','longitude' => '100.992541','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '217','name' => 'Timor-leste','code' => 'TL','latitude' => '-8.874217','longitude' => '125.727539','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '218','name' => 'Togo','code' => 'TG','latitude' => '8.619543','longitude' => '0.824782','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '219','name' => 'Tokelau','code' => 'TK','latitude' => '-8.967363','longitude' => '-171.855881','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '220','name' => 'Tonga','code' => 'TO','latitude' => '-21.178986','longitude' => '-175.198242','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '221','name' => 'Trinidad and Tobago','code' => 'TT','latitude' => '10.691803','longitude' => '-61.222503','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '222','name' => 'Tunisia','code' => 'TN','latitude' => '33.886917','longitude' => '9.537499','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '223','name' => 'Turkey','code' => 'TR','latitude' => '38.963745','longitude' => '35.243322','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '224','name' => 'Turkmenistan','code' => 'TM','latitude' => '38.969719','longitude' => '59.556278','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '225','name' => 'Turks and Caicos Islands','code' => 'TC','latitude' => '21.694025','longitude' => '-71.797928','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '226','name' => 'Tuvalu','code' => 'TV','latitude' => '-7.109535','longitude' => '177.64933','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '227','name' => 'Uganda','code' => 'UG','latitude' => '1.373333','longitude' => '32.290275','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '228','name' => 'Ukraine','code' => 'UA','latitude' => '48.379433','longitude' => '31.16558','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '229','name' => 'United Arab Emirates','code' => 'AE','latitude' => '23.424076','longitude' => '53.847818','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '230','name' => 'United Kingdom','code' => 'GB','latitude' => '55.378051','longitude' => '-3.435973','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '231','name' => 'United States','code' => 'US','latitude' => '37.09024','longitude' => '-95.712891','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '232','name' => 'United States Minor Outlying Islands','code' => 'UM','latitude' => '19.295374','longitude' => '166.6280441','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '233','name' => 'Uruguay','code' => 'UY','latitude' => '-32.522779','longitude' => '-55.765835','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '234','name' => 'Uzbekistan','code' => 'UZ','latitude' => '41.377491','longitude' => '64.585262','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '235','name' => 'Vanuatu','code' => 'VU','latitude' => '-15.376706','longitude' => '166.959158','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '236','name' => 'Venezuela','code' => 'VE','latitude' => '6.42375','longitude' => '-66.58973','continent' => 'South America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '237','name' => 'Vietnam','code' => 'VN','latitude' => '14.058324','longitude' => '108.277199','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '238','name' => 'Virgin Islands, British','code' => 'VG','latitude' => '18.420695','longitude' => '-64.639968','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '239','name' => 'Virgin Islands, U.S.','code' => 'VI','latitude' => '18.335765','longitude' => '-64.896335','continent' => 'North America','created_at' => NULL,'updated_at' => NULL),
            array('id' => '240','name' => 'Wallis and Futuna','code' => 'WF','latitude' => '-13.768752','longitude' => '-177.156097','continent' => 'Oceania','created_at' => NULL,'updated_at' => NULL),
            array('id' => '241','name' => 'Western Sahara','code' => 'EH','latitude' => '24.215527','longitude' => '-12.885834','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '242','name' => 'Yemen','code' => 'YE','latitude' => '15.552727','longitude' => '48.516388','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '243','name' => 'Zambia','code' => 'ZM','latitude' => '-13.133897','longitude' => '27.849332','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '244','name' => 'Zimbabwe','code' => 'ZW','latitude' => '-19.015438','longitude' => '29.154857','continent' => 'Africa','created_at' => NULL,'updated_at' => NULL),
            array('id' => '246','name' => 'Saint Barthelemy','code' => 'BL','latitude' => '17.9139222','longitude' => '62.8338521','continent' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '247','name' => 'Afghanistan','code' => 'AF','latitude' => '33.9340384','longitude' => '67.7034312','continent' => 'Asia','created_at' => NULL,'updated_at' => NULL),
            array('id' => '248','name' => 'Aland Islands','code' => 'AX','latitude' => '60.1996219','longitude' => '20.3711715','continent' => 'Europe','created_at' => NULL,'updated_at' => NULL),
            array('id' => '249','name' => 'Sint Maarten','code' => 'sx','latitude' => '18.0346533','longitude' => '-63.138152','continent' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '250','name' => 'Bonaire, Saint Eustatius and Saba','code' => 'bq','latitude' => '12.1683366','longitude' => '-68.4482721','continent' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '252','name' => 'Curaçao','code' => 'cw','latitude' => '12.2134833','longitude' => '-69.0896538','continent' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '253','name' => 'Saint Martin','code' => 'mf','latitude' => '18.0858588','longitude' => '-63.1321028','continent' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '254','name' => 'Kosovo','code' => 'XK','latitude' => '42.4808781','longitude' => '16.863985','continent' => NULL,'created_at' => NULL,'updated_at' => NULL)
        );

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
